//
// MoleMapper
//
// Copyright (c) 2017-2022 OHSU. All rights reserved.
//
// Redistribution and use in source and binary forms, with or without modification,
// are permitted provided that the following conditions are met:
//
// 1.  Redistributions of source code must retain the above copyright notice, this
// list of conditions and the following disclaimer.
//
// 2.  Redistributions in binary form must reproduce the above copyright notice,
// this list of conditions and the following disclaimer in the documentation and/or
// other materials provided with the distribution.
//
// 3.  Neither the name of the copyright holder(s) nor the names of any contributors
// may be used to endorse or promote products derived from this software without
// specific prior written permission. No license is granted to the trademarks of
// the copyright holders even if such marks are included in this software.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
// AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
// IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
// ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE
// FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
// DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
// SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
// CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
// OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
// OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CoinUsedRoutingLogic
{
    var photoData: TakePhoto.PhotoData? {get set}
    var molesData: ShowZone.MolesData? {get set}
    
    func navigateBack()
    func navigateToIdentifyCoin()
    func navigateToIdentifyMole()
    func retakePhoto()
}

class CoinUsedRouter: CoinUsedRoutingLogic
{
    
    var photoData: TakePhoto.PhotoData?
    var molesData: ShowZone.MolesData?
    
    weak var viewController: CoinUsedViewController?
    
    func retakePhoto() {
        viewController?.navigateBackToTakePhoto()
    }
    
    func navigateBack() {
        viewController?.navigationController?.popViewController(animated: true)
    }
    
    func navigateToIdentifyCoin() {
        let identifyCoinViewController = IdentifyCoinViewController(photoData: photoData!)
        identifyCoinViewController.modalPresentationStyle = .overFullScreen
        identifyCoinViewController.setupNavigationMenuItems(navigationType: .backNext)
        identifyCoinViewController.router?.molesData = molesData
        viewController?.navigationController?.pushViewController(identifyCoinViewController, animated: true)
    }
    
    func navigateToIdentifyMole() {
        let identifyMolesViewController = IdentifyMolesViewController(with: photoData!, andMolesData: molesData)
        identifyMolesViewController.modalPresentationStyle = .overFullScreen
        identifyMolesViewController.setupNavigationMenuItems(navigationType: .backDone)
        viewController?.navigationController?.pushViewController(identifyMolesViewController, animated: true)
    }
}
